<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pegawai;
use Carbon\Carbon;

class PegawaiSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nik'                 => '3273011501790002',
                'nip_nrk'             => '197901152006041001',
                'nama_lengkap'        => 'Dr. Ahmad Fadilah Kusumawardhana, M.Sc.',
                'jenis_kelamin'       => 'L',
                'kategori'            => 'ASN (PNS)',
                'pangkat_golongan'    => 'Pembina Utama Madya / IV-d',
                'jabatan'             => 'Kepala Dinas Lingkungan Hidup',
                'unit_kerja'          => 'Pimpinan',
                'tmt_sk'              => '2006-04-01',
                'masa_kontrak'        => 'Permanen',
                'jam_kerja_mingguan'  => 37.5,
                'pendidikan_terakhir' => 'S3 - Ilmu Lingkungan',
                'no_hp'               => '08112345601',
                'email'               => 'ahmad.fadilah@dlh.go.id',
                'status'              => 'Aktif',
            ],
            [
                'nik'                 => '3273025502810003',
                'nip_nrk'             => '198102152009032002',
                'nama_lengkap'        => 'Sri Wahyuningsih, S.Sos., M.AP.',
                'jenis_kelamin'       => 'P',
                'kategori'            => 'ASN (PNS)',
                'pangkat_golongan'    => 'Penata Tk. I / III-d',
                'jabatan'             => 'Kepala Seksi Tata Lingkungan',
                'unit_kerja'          => 'Seksi Tata Lingkungan',
                'tmt_sk'              => '2009-03-01',
                'masa_kontrak'        => 'Permanen',
                'jam_kerja_mingguan'  => 37.5,
                'pendidikan_terakhir' => 'S2 - Administrasi Publik',
                'no_hp'               => '08119876501',
                'email'               => 'sri.wahyu@dlh.go.id',
                'status'              => 'Aktif',
            ],
            [
                'nik'                 => '3273041203880005',
                'nip_nrk'             => '198803122012041003',
                'nama_lengkap'        => 'Rudi Hartono, S.T.',
                'jenis_kelamin'       => 'L',
                'kategori'            => 'ASN (PNS)',
                'pangkat_golongan'    => 'Penata Muda / III-a',
                'jabatan'             => 'Analis Lingkungan Hidup Pertama',
                'unit_kerja'          => 'Seksi Pengendalian Pencemaran',
                'tmt_sk'              => '2012-04-01',
                'masa_kontrak'        => 'Permanen',
                'jam_kerja_mingguan'  => 37.5,
                'pendidikan_terakhir' => 'S1 - Teknik Lingkungan',
                'no_hp'               => '08211122334',
                'email'               => 'rudi.hartono@dlh.go.id',
                'status'              => 'Aktif',
            ],
            [
                'nik'                 => '3273072807900007',
                'nip_nrk'             => '199007282015041001',
                'nama_lengkap'        => 'Budi Santoso, S.Kom.',
                'jenis_kelamin'       => 'L',
                'kategori'            => 'P3K Penuh Waktu',
                'pangkat_golongan'    => null,
                'jabatan'             => 'Pranata Komputer Ahli Muda',
                'unit_kerja'          => 'Sub Bagian Umum & IT',
                'tmt_sk'              => '2021-01-01',
                'masa_kontrak'        => '2026-12-31',
                'jam_kerja_mingguan'  => 37.5,
                'pendidikan_terakhir' => 'S1 - Teknik Informatika',
                'no_hp'               => '08567891234',
                'email'               => 'budi.santoso@dlh.go.id',
                'status'              => 'Aktif',
            ],
            [
                'nik'                 => '3273091505950008',
                'nip_nrk'             => '199505152020012001',
                'nama_lengkap'        => 'Dewi Rahayu Putri, S.KM.',
                'jenis_kelamin'       => 'P',
                'kategori'            => 'P3K Penuh Waktu',
                'pangkat_golongan'    => null,
                'jabatan'             => 'Epidemiolog Kesehatan Ahli Pertama',
                'unit_kerja'          => 'Seksi Kesehatan Lingkungan',
                'tmt_sk'              => '2020-01-01',
                'masa_kontrak'        => '2025-12-31',
                'jam_kerja_mingguan'  => 37.5,
                'pendidikan_terakhir' => 'S1 - Kesehatan Masyarakat',
                'no_hp'               => '08987654321',
                'email'               => 'dewi.rahayu@dlh.go.id',
                'status'              => 'Cuti',
            ],
            [
                'nik'                 => '3273102110920009',
                'nip_nrk'             => 'NRK-2022-00451',
                'nama_lengkap'        => 'Ferdi Nugraha, A.Md.',
                'jenis_kelamin'       => 'L',
                'kategori'            => 'P3K Paruh Waktu',
                'pangkat_golongan'    => null,
                'jabatan'             => 'Teknisi Laboratorium',
                'unit_kerja'          => 'Lab Pengujian Lingkungan',
                'tmt_sk'              => '2022-07-01',
                'masa_kontrak'        => '2027-06-30',
                'jam_kerja_mingguan'  => 20.0,
                'pendidikan_terakhir' => 'D3 - Analis Kimia',
                'no_hp'               => '08123344556',
                'email'               => 'ferdi.nugraha@dlh.go.id',
                'status'              => 'Aktif',
            ],
            [
                'nik'                 => '3273110809980010',
                'nip_nrk'             => 'NRK-2023-00112',
                'nama_lengkap'        => 'Lestari Handayani',
                'jenis_kelamin'       => 'P',
                'kategori'            => 'P3K Paruh Waktu',
                'pangkat_golongan'    => null,
                'jabatan'             => 'Pengadministrasi Umum',
                'unit_kerja'          => 'Sub Bagian Kepegawaian',
                'tmt_sk'              => '2023-01-02',
                'masa_kontrak'        => '2027-12-31',
                'jam_kerja_mingguan'  => 20.0,
                'pendidikan_terakhir' => 'SMA/SMK',
                'no_hp'               => '08765432100',
                'email'               => null,
                'status'              => 'Aktif',
            ],
            [
                'nik'                 => '3273120310850011',
                'nip_nrk'             => null,
                'nama_lengkap'        => 'Hendra Kusuma',
                'jenis_kelamin'       => 'L',
                'kategori'            => 'BSN / Non-ASN',
                'pangkat_golongan'    => null,
                'jabatan'             => 'Petugas Kebersihan',
                'unit_kerja'          => 'Pengelolaan Sampah',
                'tmt_sk'              => '2020-03-01',
                'masa_kontrak'        => '2026-12-31',
                'jam_kerja_mingguan'  => 40.0,
                'pendidikan_terakhir' => 'SMP',
                'no_hp'               => '08234567890',
                'email'               => null,
                'status'              => 'Aktif',
            ],
            [
                'nik'                 => '3273130705010012',
                'nip_nrk'             => null,
                'nama_lengkap'        => 'Siti Romlah, S.E.',
                'jenis_kelamin'       => 'P',
                'kategori'            => 'BSN / Non-ASN',
                'pangkat_golongan'    => null,
                'jabatan'             => 'Staf Keuangan Honorer',
                'unit_kerja'          => 'Sub Bagian Keuangan',
                'tmt_sk'              => '2021-09-01',
                'masa_kontrak'        => '2026-08-31',
                'jam_kerja_mingguan'  => 37.5,
                'pendidikan_terakhir' => 'S1 - Akuntansi',
                'no_hp'               => '08998877665',
                'email'               => 'siti.romlah@gmail.com',
                'status'              => 'Aktif',
            ],
            [
                'nik'                 => '3273141204780014',
                'nip_nrk'             => '197804122000031004',
                'nama_lengkap'        => 'Drs. Suprapto, M.M.',
                'jenis_kelamin'       => 'L',
                'kategori'            => 'ASN (PNS)',
                'pangkat_golongan'    => 'Pembina / IV-a',
                'jabatan'             => 'Kepala Sub Bagian Umum & Kepegawaian',
                'unit_kerja'          => 'Sub Bagian Umum & Kepegawaian',
                'tmt_sk'              => '2000-03-01',
                'masa_kontrak'        => 'Permanen',
                'jam_kerja_mingguan'  => 37.5,
                'pendidikan_terakhir' => 'S2 - Manajemen',
                'no_hp'               => '08111230004',
                'email'               => 'suprapto@dlh.go.id',
                'status'              => 'Tugas Belajar',
            ],
        ];

        foreach ($data as $item) {
            Pegawai::create($item);
        }
    }
}
